# Generated by Django 3.1.3 on 2021-02-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('bakeryitemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=100)),
                ('makingcharges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredientId', models.AutoField(primary_key=True, serialize=False)),
                ('ingredientname', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('costprice', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('cardId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('customerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ingredients')),
                ('itemId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bakeryitem')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='itemId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.itemingredient'),
        ),
    ]
