# Generated by Django 3.1.3 on 2021-02-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_regsiteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsiteration',
            name='gender',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regsiteration')),
            ],
        ),
    ]
