# Generated by Django 3.1.3 on 2021-02-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regsiteration',
            name='user',
        ),
        migrations.CreateModel(
            name='CustomerRegsiteration',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=8)),
                ('mobileno', models.CharField(max_length=10)),
                ('countrycode', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customerregsiteration'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customerregsiteration'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Regsiteration',
        ),
    ]
