# Generated by Django 3.1.3 on 2021-02-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210224_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cardId',
            new_name='cartId',
        ),
    ]
