# Generated by Django 3.1.3 on 2021-02-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210224_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='costprice',
            field=models.CharField(max_length=100),
        ),
    ]
