# Generated by Django 3.1.3 on 2021-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210224_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingredient',
            name='quantitypercentage',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='makingcharges',
            field=models.CharField(max_length=100),
        ),
    ]
