# Generated by Django 3.1.3 on 2021-02-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210224_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='ingredientslist',
            field=models.JSONField(default=[{'name': 'oil', 'quantityper': 10}, {'name': 'egg', 'quantityper': 20}, {'name': 'milk', 'quantityper': 12}, {'name': 'flour', 'quantityper': 30}]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='itemId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bakeryitem'),
        ),
        migrations.DeleteModel(
            name='ItemIngredient',
        ),
    ]
